---
- name: Write global bashrc
  ansible.builtin.copy:
    src: bash.bashrc
    dest: /etc/bash.bashrc
    owner: root
    group: root
    mode: "0644"

- name: Write root and skeleton .bashrc
  ansible.builtin.copy:
    src: .bashrc
    dest: "{{ item }}/.bashrc"
    owner: root
    group: root
    mode: "0644"
  with_items:
    - /root
    - /etc/skel

- name: Determine ssh user homedir
  ansible.builtin.shell: "set -o pipefail && getent passwd {{ item }} | cut -d: -f6"
  register: bashrc_homedirs
  with_items: "{{ bashrc_users }}"
  changed_when: false

- name: Write ssh user homedir .bashrc
  ansible.builtin.copy:
    src: .bashrc
    dest: "{{ item.stdout }}/.bashrc"
    owner: "{{ item.item }}"
    group: "{{ item.item }}"
    mode: "0644"
  with_items: "{{ bashrc_homedirs.results }}"
