---

- name: write global bashrc
  copy: src=bash.bashrc dest=/etc/bash.bashrc owner=root group=root mode=0644

- name: write root and skeleton .bashrc
  copy: "src=.bashrc dest={{ item }}/.bashrc owner=root group=root mode=0644"
  with_items:
    - /root
    - /etc/skel

- name: determine ssh user homedir
  shell: "getent passwd {{ ansible_ssh_user }} | cut -d: -f6"
  register: bashrc_homedir
  changed_when: False

- name: write ssh user homedir .bashrc
  copy: "src=.bashrc dest={{ bashrc_homedir.stdout }}/.bashrc owner={{ ansible_ssh_user }} group={{ ansible_ssh_user }} mode=0644"
